name: build-windows

on:
  workflow_call: {}

env:
  APP_NAME: credcalc
  ENTRY: main.py
  ICON: assets/icon.ico

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }
          python -m pip install pyinstaller

      - name: Build (PyInstaller)
        shell: bash
        run: |
          EXTRA_ICON=""
          if [ -n "${ICON}" ]; then EXTRA_ICON="--icon=${ICON}"; fi
          pyinstaller --clean --windowed --onefile ${EXTRA_ICON} --name "${APP_NAME}" "${ENTRY}"
          mkdir -p release
          cp dist/${APP_NAME} release/yourapp-windows-x64.exe
          (cd release && zip -r ${APP_NAME}-windows-x64.zip ${APP_NAME}-windows-x64.exe)
          (cd release && sha256sum ${APP_NAME}-windows-x64.exe ${APP_NAME}-windows-x64.zip > SHA256SUMS-windows.txt)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-assets
          path: release/*