name: build-linux

on:
  workflow_call: {}

permissions: { contents: read }

env:
  APP_NAME: credcalc
  ENTRY: main.py
  ICON: assets/icon.ico

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pyinstaller

      - name: Build
        run: |
          EXTRA_ICON=""
          if [ -n "${ICON}" ]; then EXTRA_ICON="--icon=${ICON}"; fi
          pyinstaller --clean --windowed --onefile ${EXTRA_ICON} --name "${APP_NAME}" "${ENTRY}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-assets
          path: dist/*
