name: build-windows

on:
  workflow_call:
    inputs:
      icon:
        type: string
        required: true
      entry-point:
        type: string
        required: true
      app-name:
        type: string
        required: true
      python_ver:
        type: string
        description: specific python version you want to use
        default: '3.12'
      python_arch:
        type: string
        description: specific python architecture you want to use
        default: 'x64'
      exe_path:
        type: string
        description: Path on runner-os, where generated executable files are stored
        default: './dist'
      upload_exe_with_name:
        type: string
        description: If passed, uploads executable artifact  with this name. Else, artifact won't be uploaded.
        default: ''


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_ver }}
          architecture: ${{ inputs.python_arch }}
          cache: 'pip'

      - name: Install deps
        shell: bash
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pyinstaller

      - name: Create Executable
        shell: bash
        run: |
          pyinstaller \
            --clean \
            --windowed \
            --onefile \
            --icon=${{ inputs.icon }} \
            --name ${{ inputs.app-name }} \
            ${{ inputs.entry-point }} \

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.upload_exe_with_name }}
          path: ${{ inputs.exe_path }}