name: Build Linux

on:
  push:
    branches: [ master, dev ]
    paths-ignore: [ '**.md', '**/*.txt' ]
  pull_request:

permissions: { contents: read }

env:
  APP_NAME: credcalc
  ENTRY: main.py
  ICON: assets/icon.ico

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: (Optional) Tk for GUI apps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk || true

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pyinstaller

      - name: Build (PyInstaller)
        run: |
          EXTRA_ICON=""
          if [ -n "${ICON}" ]; then EXTRA_ICON="--icon=${ICON}"; fi
          pyinstaller --clean --windowed --onefile ${EXTRA_ICON} --name "${APP_NAME}" "${ENTRY}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-linux
          path: dist/${{ env.APP_NAME }}
